name: Trigger Renovate

on:
  workflow_dispatch:  # Allows for manual trigger
  schedule:
    - cron: "0 0 * * *"  # Optional: Run daily at midnight

jobs:
  renovate:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:jammy
    steps:
      - name: Set up environment
        run: |
          apt-get update && apt-get install -y git curl gnupg2 lsb-release ca-certificates
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs
          apt-get install -y python3 python3-pip python3-venv
          apt-get install -y ruby-full

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Renovate
        run: npm install -g renovate

      - name: Run Renovate
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: "babywyrm/demo"  # Specify the repository
        run: renovate --autodiscover=false
        
