name: Do Renovate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  renovate:
    runs-on: [self-hosted, hot-new-new]  # Use your custom runner label 'hot-new-new'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Renovate
        uses: renovatebot/github-action@v40.2.2
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: "babywyrm/demo"  # Specify the repository
        with:
          args: "--autodiscover=false"
