version: 2
updates:
  # Python dependencies
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly        # Options: daily, weekly, monthly
      time: "13:00"           # Specify time in UTC
      day: monday             # Options: monday, tuesday, etc. (for weekly)
    pull-request-branch-name:
      separator: "-"          # Custom branch naming
    open-pull-requests-limit: 10
    labels:
      - type:dependencies
      - release:main
    ignore:
      - dependency-name: prompt-toolkit
        versions:
          - "> 2.0.10"
      - dependency-name: pytest-asyncio
        versions:
          - "> 0.10.0"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"       # Options: scope, type, none
    assignees:
      - dev-team             # Automatically assign PRs to a team or user
    reviewers:
      - lead-developer       # Assign reviewers
    milestone: "Next Release" # Automatically add milestone
    rebase-strategy: auto     # Options: auto, disabled
    # Optionally add custom versioning rules
    versioning-strategy: widen # Options: increase, widen, lockfile-only

  # JavaScript/Node.js dependencies
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
    pull-request-branch-name:
      separator: "_"
    open-pull-requests-limit: 5
    labels:
      - javascript
      - dependencies
    ignore:
      - dependency-name: lodash
        versions:
          - "< 4.0.0"
    commit-message:
      prefix: "fix(deps)"
      include: "none"
    reviewers:
      - js-team
    # Auto-merge option when conditions are met
    automerged_updates:
      - match:
          dependency_type: all  # Options: production, development, all
          update_type: "semver:minor"

  # Docker dependencies
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: monthly
      day: friday
      time: "14:00"
    pull-request-branch-name:
      separator: "/"
    open-pull-requests-limit: 2
    labels:
      - docker
      - security
    ignore:
      - dependency-name: nginx
        versions:
          - "< 1.19.0"
    reviewers:
      - devops-team
    milestone: "Q4 Release"

  # GitHub Actions workflows
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      time: "10:00"
    pull-request-branch-name:
      separator: "_"
    open-pull-requests-limit: 5
    labels:
      - github-actions
      - dependencies
    ignore:
      - dependency-name: actions/checkout
        versions:
          - "< 2.3.0"
    reviewers:
      - actions-team
    automerged_updates:
      - match:
          dependency_type: all
          update_type: "semver:minor"

  # Ruby dependencies (Bundler)
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
    pull-request-branch-name:
      separator: "_"
    open-pull-requests-limit: 5
    labels:
      - ruby
      - dependencies
    ignore:
      - dependency-name: rails
        versions:
          - "> 6.0.0"
    reviewers:
      - backend-team
    rebase-strategy: auto
    milestone: "v1.0.0"
    versioning-strategy: increase

  # Terraform modules
  - package-ecosystem: terraform
    directory: "/"
    schedule:
      interval: weekly
      day: thursday
      time: "07:00"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 3
    labels:
      - terraform
      - infrastructure
    ignore:
      - dependency-name: "hashicorp/aws"
        versions:
          - "> 3.0.0"
    reviewers:
      - infra-team
    milestone: "Next Major Release"
    automerged_updates:
      - match:
          dependency_type: production

  # Maven dependencies (Java)
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: monthly
      day: wednesday
      time: "08:00"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 5
    labels:
      - java
      - dependencies
    ignore:
      - dependency-name: com.fasterxml.jackson.core
        versions:
          - "< 2.12.0"
    reviewers:
      - java-team
    rebase-strategy: disabled

  # Go dependencies (Go Modules)
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "05:00"
    pull-request-branch-name:
      separator: "/"
    open-pull-requests-limit: 3
    labels:
      - golang
      - dependencies
    commit-message:
      prefix: "chore(deps)"
      include: "type"
    reviewers:
      - golang-team
    rebase-strategy: auto

  # NuGet dependencies (C#/.NET)
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    pull-request-branch-name:
      separator: "_"
    open-pull-requests-limit: 2
    labels:
      - dotnet
      - dependencies
    reviewers:
      - dotnet-team
    automerged_updates:
      - match:
          update_type: "semver:minor"

##
##


##
##
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: "13:00"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10
    labels:
      - type:dependencies
      - release:main
    ignore:
      - dependency-name: prompt-toolkit
        versions:
          - "> 2.0.10"
      - dependency-name: pytest-asyncio
        versions:
          - "> 0.10.0"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "12:00"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10
    reviewers:
      - RasaHQ/infrastructure-squad
    labels:
      - type:dependencies

##
##
