name: Renovate Weekly

# 1) Schedule + manual trigger
on:
  schedule:
    # every Sunday at 01:00 UTC
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  renovate:
    # Use GitHub-hosted runner
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed for Renovate to push branches/PRs
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovate/renovate-action@v38
        with:
          # points at your config file
          config-file: .github/renovate.json
        env:
          # GitHub App token (supplied by GitHub)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
