apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless-chrome
  namespace: default
  labels:
    app: headless-chrome
spec:
  replicas: 2
  selector:
    matchLabels:
      app: headless-chrome
  template:
    metadata:
      labels:
        app: headless-chrome
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
      containers:
      - name: headless-chrome
        image: your-dockerhub-user/headless-chrome-node:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        readinessProbe:
          httpGet:
            path: /screenshot?url=https://example.com
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 60
