{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  annotations:
    {{- range $k, $v := .Values.serviceAccount.annotations }}
    {{ $k }}: "{{ $v }}"
    {{- end }}
{{- end }}
