##
##
##

apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: global-headers
  namespace: ambassador
spec:
  prefix: / # This applies to all routes
  service: httpbin.org # Example service, replace with your service
  add_request_headers:
    X-Content-Type-Options: "nosniff"
    X-Frame-Options: "DENY"
    X-XSS-Protection: "1; mode=block"
    Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
    Referrer-Policy: "no-referrer"
    Feature-Policy: "geolocation 'none'; microphone 'none'; camera 'none'"
    Content-Security-Policy: |
      default-src 'none';
      script-src 'self';
      connect-src 'self';
      img-src 'self';
      style-src 'self';
      font-src 'self';
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "GET, POST, OPTIONS"
    Access-Control-Allow-Headers: "Content-Type, Authorization"
    Access-Control-Allow-Credentials: "true"
  cors:
    origins: "*"
    methods:
    - GET
    - POST
    - OPTIONS
    headers:
    - Content-Type
    - Authorization
    credentials: true
    max_age: "86400" # Cache pre-flight response for 24 hours



##
##
##

X-Content-Type-Options: "nosniff": Prevents the browser from MIME-sniffing a response away from the declared content-type.

X-Frame-Options: "DENY": Protects against clickjacking by preventing the site from being framed.

X-XSS-Protection: "1; mode=block": Enables XSS filtering and prevents rendering the page if an attack is detected.

Strict-Transport-Security: Enforces secure (HTTPS) connections to the server.

Referrer-Policy: Controls the amount of referrer information sent with requests.

Feature-Policy: Restricts or allows the use of browser features within the website.

Content-Security-Policy: The most critical header for mitigating XSS attacks. This example restricts the sources from which content can be loaded.

Access-Control-Allow-Origin: Specifies the origin allowed to access the resources. Adjust the wildcard * to specific domains as needed.

Access-Control-Allow-Methods: Specifies the methods allowed when accessing the resource.

Access-Control-Allow-Headers: Indicates which headers are allowed when making the request.

cors: This section configures CORS policies specifically, including allowed origins, methods, and headers.
