
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs
  namespace: "rsyslog"
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: aws-efs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /
    server: fs-xxxx.efs.ap-southeast-1.amazonaws.com
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs
  namespace: "rsyslog"
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
