apiVersion: v1
kind: Service
metadata:
  name: "rsyslog"
  namespace: "rsyslog"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    alb.ingress.kubernetes.io/scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "environment=stage,app=rsyslog"

spec:
  ports:
    - port: 514
      targetPort: 514
      protocol: TCP
  type: LoadBalancer
  selector:
    app: "rsyslog"
