apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: IPAddressPool
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"metallb.io/v1beta1","kind":"IPAddressPool","metadata":{"annotations":{},"name":"default","namespace":"metallb-system"},"spec":{"addresses":["192.168.1.191-192.168.1.195"]}}
    creationTimestamp: "2025-03-16T22:13:31Z"
    generation: 1
    name: default
    namespace: metallb-system
    resourceVersion: "13355"
    uid: 09da442c-5fc8-4426-b87c-8cd53209776e
  spec:
    addresses:
    - 192.168.1.191-192.168.1.195
    autoAssign: true
- apiVersion: metallb.io/v1beta1
  kind: L2Advertisement
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"metallb.io/v1beta1","kind":"L2Advertisement","metadata":{"annotations":{},"name":"default","namespace":"metallb-system"},"spec":{"ipAddressPools":["default"]}}
    creationTimestamp: "2025-03-16T22:13:31Z"
    generation: 1
    name: default
    namespace: metallb-system
    resourceVersion: "13360"
    uid: 6d41173e-1f2c-49f0-8299-1d1764dddcf5
  spec:
    ipAddressPools:
    - default
kind: List
metadata:
  resourceVersion: ""
