# config/opa/templates/signed-images-template.yaml
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: signedimagesonly
spec:
  crd:
    spec:
      names:
        kind: SignedImagesOnly
      validation:
        properties:
          allowedRegistries:
            type: array
            items:
              type: string
          cosignPublicKey:
            type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package signedimagesonly

        violation[{"msg": msg}] {
          input.review.object.kind == "Pod"
          image := input.review.object.spec.containers[_].image

          # 1) registry must be allowed
          not startswith(image, input.parameters.allowedRegistries[_])
          msg := sprintf("Image %v not in allowed registries", [image])
        }

        violation[{"msg": msg}] {
          input.review.object.kind == "Pod"
          image := input.review.object.spec.containers[_].image

          # 2) image must have valid cosign signature
          not image_has_valid_signature(image, input.parameters.cosignPublicKey)
          msg := sprintf("Image %v missing valid cosign signature", [image])
        }

---
# config/opa/constraints/signed-images.yaml
apiVersion: config.gatekeeper.sh/v1alpha1
kind: SignedImagesOnly
metadata:
  name: projectx-signed-images
spec:
  allowedRegistries:
    - "registry-tier1.project-x.local/ctf/tier1"
    - "registry-tier2.project-x.local/ctf/tier2"
    - "registry-tier3.project-x.local/ctf/tier3"
  cosignPublicKey: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE...
    -----END PUBLIC KEY-----
