apiVersion: apps/v1
kind: Deployment
metadata:
  name: nightingale
  labels:
    app: nightingale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nightingale
  template:
    metadata:
      labels:
        app: nightingale
    spec:
      containers:
      - name: nightingale
        image: your-registry/nightingale:latest
        ports:
        - containerPort: 8080
        # Pass target information via environment variables (if supported)
        env:
        - name: TARGET_URL
          value: "http://staging-target.example.com"
        # Optionally override the command if dynamic behavior is needed
        command: ["python", "Nightingale.py"]
