version: '2'
services:
  deadly-sso:
    build: .
    image: sso:beta
    container_name: deadly-sso-beta
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
      
