version: '3'
services:
  app:
    build: .
    ports:
      - 5000:5000
    environment:
      - DB_HOST=<db_host>
      - DB_USERNAME=<db_username>
      - DB_PASSWORD=<db_password>
      - DB_NAME=<db_name>
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=<db_name>
      - MYSQL_USER=<db_username>
      - MYSQL_PASSWORD=<db_password>
      - MYSQL_ROOT_PASSWORD=<db_root_password>
    volumes:
      - ./data:/var/lib/mysql
