# ─────────────────────────────────────────────────────────────────────────────
# templates/externalsecret.yaml
#
# Creates an ExternalSecret resource (External Secrets Operator).
# ESO watches this resource and syncs the specified secret from an external
# provider (Vault, AWS SM, GCP SM, etc.) into a K8s Secret.
#
# Why this matters:
#   Without ESO, you would put credentials in values.yaml, which lands
#   them in the Helm release secret — readable by anyone with `get secrets`.
#   With ESO, credentials never touch Helm at all.
#
# Prerequisites:
#   - External Secrets Operator installed in cluster
#   - A ClusterSecretStore named in .Values.externalSecret.secretStoreRef
#   - The gateway SA has Vault policy (or equivalent) to read the secret path
#
# Install ESO:
#   helm repo add external-secrets https://charts.external-secrets.io
#   helm install external-secrets external-secrets/external-secrets \
#     -n external-secrets-system --create-namespace
# ─────────────────────────────────────────────────────────────────────────────
{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "agentgateway.fullname" . }}-ext-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentgateway.labels" . | nindent 4 }}
spec:
  # How often ESO checks the external provider for changes and re-syncs.
  # Set lower (e.g., "5m") if secrets rotate frequently.
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}

  # Reference to the SecretStore or ClusterSecretStore that defines
  # how ESO authenticates to your secrets backend.
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}

  target:
    # Name of the K8s Secret ESO will create/maintain
    name: {{ .Values.externalSecret.target.name }}

    # Owner: ESO owns the secret lifecycle (deletes it when ES is deleted)
    creationPolicy: Owner

    template:
      metadata:
        annotations:
          # Prevent Helm from managing this secret directly.
          # Helm would otherwise try to delete it on uninstall and conflict
          # with ESO's ownership.
          helm.sh/resource-policy: keep

  # Mapping of external secret keys to K8s secret keys.
  # Each entry pulls one field from the external provider.
  data:
    {{- toYaml .Values.externalSecret.data | nindent 4 }}

{{- end }}
